-- SELECT top 10
SELECT * FROM ASSESSMENT LIMIT 10;
SELECT * FROM CITY LIMIT 10;
SELECT * FROM CIVIC_LOCATION LIMIT 10;
SELECT * FROM MUNICIPALITY LIMIT 10;
SELECT * FROM ORDERS LIMIT 10;
SELECT * FROM PARK LIMIT 10;
SELECT * FROM REVIEW LIMIT 10;
SELECT * FROM TRANSACTIONS LIMIT 10;
SELECT * FROM TREE LIMIT 10;
SELECT * FROM USERS LIMIT 10;
SELECT * FROM WORKS_FOR LIMIT 10;
