
-- Select Statements
SELECT * FROM ASSESSMENT;
SELECT * FROM CITY;
SELECT * FROM CIVIC_LOCATION;
SELECT * FROM MUNICIPALITY;
SELECT * FROM ORDERS;
SELECT * FROM PARK;
SELECT * FROM REVIEW;
SELECT * FROM TRANSACTIONS;
SELECT * FROM TREE;
SELECT * FROM USERS;
SELECT * FROM WORKS_FOR;
